# Generated by Django 4.1.3 on 2023-01-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="Rei Receitas", max_length=100),
        ),
    ]
