# Generated by Django 4.1.3 on 2023-01-13 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_revenue",
                    models.CharField(max_length=100, verbose_name="Nome da receita"),
                ),
                ("ingredients", models.TextField(verbose_name="Ingredientes")),
                ("preparation_mode", models.TextField(verbose_name="Modo de preparo")),
                (
                    "revenue_image",
                    models.ImageField(
                        blank=True,
                        default="images/image_notfound.jpg",
                        null=True,
                        upload_to="images/",
                        verbose_name="Passe uma imagem ou foto para esta receita",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                ("updated", models.DateField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "like",
                    models.ManyToManyField(
                        related_name="like", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.topic",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="message", name="recipe",),
        migrations.DeleteModel(name="Recipe",),
        migrations.AddField(
            model_name="message",
            name="revenue",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.revenue",
            ),
        ),
    ]
